### ISSUE TITLE
PM Feedback on the getting started guide

### ISSUE THREAD

**Issue by jclingan** [openshiftio/appdev-documentation#107]
A lot of feedback here in one issue instead of creating 10 different issues.

- In the intro paragraph, "using ConfigMap" should be “using externalized configuration”. I’d prefer stating the concept rather than the implementation in the getting started guide.

- Section 1 - A very brief description of Minishift would be nice, like “Minishift runs the OpenShift Container Platform using a virtual machine technology supported by your operating system”.
- Step 2.1 - We should probably briefly describe what a project is. Most developers will think that a project is some kind of IDE project instead of an OpenShift project.
- Step 2.1.2 - “Select begin” should now be “Push the “Prepare for Takeoff button” or similar message
- Step 2.2.1 - “Once your mission is deployed”. We will want to set expectations here with some time frame. “Building and deploying a mission can take 5 minutes or more as it downloads all of the maven and docker artifacts required to deploy the application”. DevExp team can provide a good estimate.
- Step 2.2.2 . “Download Zip and follow the instructions in the mission’s guide”, Perhaps we should specify the Readme.md?
- Step 2.3.2.4. “oc login Minishift_URL — token MYTOKEN” I simply logged in with “oc login MINISHIFT_URL”, and used default credentials. Easier than explaining how to get the token, unless we plan to use the token elsewhere.
- Step 3 - Perhaps we should add a warning about running too many projects on the VM. “Our recommendation is to run no more than X number of projects at any one time in the default configuration.

**Comment by ALRubinger** [comment]
@jclingan Thank you for this feedback; I'm folding it into my review as well on this guide and will handle here.

RE: 2.2.2, the README is no longer the authoritative place for the Booster docs; the docs as listed are. :)

@rhoads-zach Ready for your review in https://github.com/openshiftio/appdev-documentation/pull/108
