### ISSUE TITLE
Wrong ConfigMap content

### ISSUE THREAD

**Issue by gytis** [openshiftio/appdev-documentation#112]
I'm not sure how it is for Vert.x and Swarm, but Spring Boot ConfigMap content is different from the one defined in the docs step 3.1.1. Actual content is:

    apiVersion: v1
    data:
      application.properties: |
        greeting.message: Hello %s from a ConfigMap!
    ...

**Comment by heiko-braun** [comment]
@gytis you refer to the `greeting.message` value I assume?

**Comment by gytis** [comment]
@heiko-braun value and properties file name. See here: http://openshiftio-appdev-docs-appdev-documentation.tsrv.devshift.net/mission-configmap-spring-boot-tomcat.html. For spring it should be application.properties not app-config.yml.

**Comment by heiko-braun** [comment]
https://github.com/openshiftio/appdev-documentation/pull/116
