### ISSUE TITLE
Increase the docs base font size to 16px

### ISSUE THREAD

**Issue by heiko-braun** [openshiftio/appdev-documentation#115]
At a quick glance 16px seems common across sites that encourage reading. I think we should use the same.

**Comment by cmoulliard** [comment]
The rendered HTML doesn't look great. 

Why do we use patternfly css instead of one the asciidoctor styles (https://github.com/asciidoctor/asciidoctor-stylesheet-factory/tree/master/sass) or default asciidoctor style ?

**Comment by heiko-braun** [comment]
Or like this https://docs.openshift.org/latest/welcome/index.html

**Comment by cmoulliard** [comment]
Here is the doc generated using the default asciidoctor stylesheet

<img width="1391" alt="screenshot 2017-04-19 16 39 19" src="https://cloud.githubusercontent.com/assets/463790/25186209/cdd033c4-251f-11e7-831f-a0f0a00953a9.png">

asciibinder uses a different css file that I will try to use

Remark : The existing site generated contains a reference to a style that we don't need 

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/github.min.css">
```

**Comment by rhoads-zach** [comment]
Closing this issue as per https://github.com/edewit/appdev-documentation/commit/b28c7326836cb6d7b2259ad0511bf084d12a85f3
