### ISSUE TITLE
{app-name} variable no longer applies

### ISSUE THREAD

**Issue by kenfinnigan** [openshiftio/appdev-documentation#117]
Currently the {app-name} property is set for each booster runtime as a property to be replaced in various doc usage.

Unfortunately the boosters are now using {project.artifactId} in their builds which means the name for {app-name} is entirely dependent on what the user specifies in the Launchpad UI.

**Comment by heiko-braun** [comment]
@rhoads-zach It looks like `{app-name}` is now substituted with `PROJECT_NAME`:
![screen shot 2017-04-20 at 08 50 31](https://cloud.githubusercontent.com/assets/369380/25217271/8210a928-25a6-11e7-9452-fd754b01cf4b.png)

Which seems wrong. 

@kenfinnigan Why does  {project.artifactId} changes when booster are cloned through the launchpad? Overall this change seems to do more damage than good to me.

**Comment by heiko-braun** [comment]
@rhoads-zach Should we reopen this one to revisit the problem?

**Comment by heiko-braun** [comment]
Another example from the current docs:
![screen shot 2017-04-20 at 08 56 28](https://cloud.githubusercontent.com/assets/369380/25217448/462a5b56-25a7-11e7-9188-fd2d5a11e746.png)

**Comment by kenfinnigan** [comment]
@heiko-braun this change is necessary because the ${project.artifactId} is not fixed when cloned through the Launchpad.

Each user gives the project a unique name
