### ISSUE TITLE
Minishift install points to launchpad v2 instructions

### ISSUE THREAD

**Issue by heiko-braun** [openshiftio/appdev-documentation#132]
See the link in http://openshiftio-appdev-docs-appdev-documentation.tsrv.devshift.net/minishift-installation.html that takes you to the `template.yml`

**Comment by rhoads-zach** [comment]
@heiko-braun this is the correct link now, correct?
https://raw.githubusercontent.com/openshiftio/launchpad-templates/v3/openshift/launchpad-template.yaml

**Comment by heiko-braun** [comment]
yes, that's the one

**Comment by heiko-braun** [comment]
we might actually substitute `v3` with a variable somewhere in the docs processing chain

**Comment by rhoads-zach** [comment]
working on a solution now that will hopefully solve this.

**Comment by ALRubinger** [comment]
d8506d0
