### ISSUE TITLE
Launchpad install script points to wrong version of the catalog

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#141]
When installing the launchpad through the automatic script, the launchpad was showing all 6 boosters instead of just CRUD, Healtcheck and REST

**Comment by rhoads-zach** [comment]
@cmoulliard mind taking a look?

**Comment by cmoulliard** [comment]
@rhoads-zach Do we have to use a specific tag or master is correct (https://github.com/openshiftio/appdev-documentation/blob/master/scripts/deploy_launchpad_mission.sh#L77-L78) ?

**Comment by rhoads-zach** [comment]
I believe that is an @gastaldi question

**Comment by gastaldi** [comment]
@cmoulliard @rhoads-zach When a release train happens, we tag the template, changing the default values of these ENV vars to the correct values. Master is used only for development. 

The tagged template has these values already set, so you must not override it. So if your script could just point to the tagged template and not override `LAUNCHPAD_BACKEND_CATALOG_GIT_REF` that should be enough.

**Comment by cmoulliard** [comment]
@gastaldi So do you suggest to remove these lines ?

```
    -p LAUNCHPAD_BACKEND_CATALOG_GIT_REF=master \
    -p LAUNCHPAD_BACKEND_CATALOG_INDEX_PERIOD="0" \
```

or just

```
    -p LAUNCHPAD_BACKEND_CATALOG_GIT_REF=master \
```

**Comment by gastaldi** [comment]
Remove all env vars that begin with `LAUNCHPAD_BACKEND_CATALOG`

**Comment by cmoulliard** [comment]
see https://github.com/openshiftio/appdev-documentation/pull/149

**Comment by gastaldi** [comment]
Merged in https://github.com/openshiftio/appdev-documentation/commit/723a61f4e84b9a35ef1816765ce48a8d1829bc89
