### ISSUE TITLE
Externalize latest template version; add to release train instructions to update this

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#142]
Introduced by d8506d013cffafc073861be8864a1b2aafb8f7f9; externalize the URL used by Vert.x as the indirection to `latest`

**Comment by rhoads-zach** [comment]
@tradej do you mind grabbing this one?

**Comment by tradej** [comment]
I certainly do not.

**Comment by ALRubinger** [comment]
So @tradej the line in question is here:

`private static final String LAUNCHER_TEMPLATE_LATEST_URL = "https://raw.githubusercontent.com/openshiftio/launchpad-templates/v4/openshift/launchpad-template.yaml";`

...in `./ci/openshiftio-appdev-docs/src/main/java/io/openshift/appdev/documentation/builder/HttpApplication.java`

We'd like to fix this such that the URL there is externalized by some mechanism so that we don't need to update source files as part of the release process.  How that's done is something you may recommend. :)
