### ISSUE TITLE
Create Wiki Page: Status of Boosters

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#15]
Let's create a table of all known Boosters under our control, and the state they're in.  

Blocking under Mission finalization
Ready for Developer
Under Development
Ready for QE
Maintenance

**Comment by rhoads-zach** [comment]
@ALRubinger do you want this as the main wiki page? or a different page?

**Comment by kenfinnigan** [comment]
@rhoads-zach, personally the main wiki page is the best place

**Comment by rhoads-zach** [comment]
@ALRubinger @kenfinnigan I've created an initial page here:
https://github.com/openshiftio/appdev-documentation/wiki

Closing this issue for now.

I'll assume as Missions are added the page will be updated. Also, the status should be updated by the mission owner or @ALRubinger

**Comment by kenfinnigan** [comment]
Thanks @rhoads-zach !
