### ISSUE TITLE
Consistent Mission/Booster titles

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#150]
Align the booster/mission titles with the index.html pages in each project

**Comment by rhoads-zach** [comment]
@kenfinnigan @cmoulliard @ALRubinger FYI

**Comment by heiko-braun** [comment]
@rhoads-zach done for swarm

**Comment by gytis** [comment]
@heiko-braun did you change only title and h1 tags? If docs are not going to change any more, we should update the rest of the text in index.html too maybe?

**Comment by heiko-braun** [comment]
@gytis I did take the title from the docs and used it for the HTML `<title>` and the first headline in the `index.html`. Is this what you had in mind?

**Comment by gytis** [comment]
OK updated Spring boot

**Comment by rhoads-zach** [comment]
@cmoulliard did you already do this for vert.x?

**Comment by rhoads-zach** [comment]
@gytis @cescoffier @cmoulliard @heiko-braun 

Here are the current mission names i have in the docs:

REST API Level 0 Mission
ConfigMap Mission
CRUD Mission
Health Check Mission

Is there any more work on normalizing them across the boosters or can i close this?

**Comment by rhoads-zach** [comment]
Closing. Please re-open if there is more work needed
