### ISSUE TITLE
Temporarily remove "modify" Booster sections

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#16]
@rhoads-zach This guidance is one that I stand behind, but I think we're scoped too widely for Summit.

The instructions to enhance the Boosters in an expert mode open up some questions:
1) How do we test the docs to ensure they leave the user with functioning apps?
2) How do we keep changes to the instructions in sync?
3) Do we attempt these for all Missions for consistency?

Let's scope ourselves down, remove these sections for now, and revisit to do this in a comprehensive fashion later.  Cool?

**Comment by rhoads-zach** [comment]
@ALRubinger since #20 resolved this issue, i'm closing
