### ISSUE TITLE
Icons of font-awesome are too small

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#163]
<img width="998" alt="screenshot 2017-04-24 19 14 26" src="https://cloud.githubusercontent.com/assets/463790/25349498/5ac09566-2922-11e7-9129-376395297212.png">

**Comment by inoxx03** [comment]
fixed in PR #233

**Comment by inoxx03** [comment]
Context: The icon sizing problem seems to occur when using the foundation.css style sheet, where the font size has been set globally for all icons to 2.5em. This however, ignored the admonition block classes (for example ".admonitionblock td.icon .icon-note:before") , where the icon size remained default and, therefore, too small.
I've managed to work around this by setting the font size _individualy_ for each admonition block class to 2.5em.
The icons should now be displayed correctly even when using the foundation.css stylesheet.

**Comment by inoxx03** [comment]
![icon_size_fixed](https://cloud.githubusercontent.com/assets/17914654/25998881/3732ca56-3723-11e7-97a9-15996d59f057.png)

The icons are currently rendered as seen above:

**Comment by rhoads-zach** [comment]
@inoxx03 should this still be open?

**Comment by inoxx03** [comment]
@rhoads-zach I'm sure this has been fixed already. in PR #233. No need to keep it open.  Closing.
