### ISSUE TITLE
Replace CRUD mission verbiage with something more "compelling"

### ISSUE THREAD

**Issue by jclingan** [openshiftio/appdev-documentation#164]
CRUD is not descriptive enough Launchpad mission name. We can discuss are more compelling alternative, but "Database Backend" is more descriptive. Willing to discuss additional alternative naming options as well.

This is going to require a documentation change in addition to a change and to the launchpad frontend for sure. If the backend keys off the mission name, then this may also require launchpad backend changes.

This change can wait until after Red Hat summit.

**Comment by cmoulliard** [comment]
I agree with you John as CRUD is the name of a pattern & not really representative of what we want to do. I propose as mission name which should be "Database persistence using JPA", "Database connection with JDBC", ...

**Comment by rhoads-zach** [comment]
@inoxx03 are you still working on this or can this issue be closed?

**Comment by inoxx03** [comment]
@rhoads-zach TBH, I thought we've deprioritized this, so I have not made any changes based on this issue. Please leave it open for now.

**Comment by inoxx03** [comment]
@jclingan @cmoulliard @edewit @gastaldi Out of the alternatives proposed above I personally favor `Database Backend` as the new name for the CRUD Mission. If you have any other name suggestions, please let me know, but I'm OK with renaming the Mission to 'Database Backend'.

**Comment by gastaldi** [comment]
`Database Backend` looks good, but should we specify that it means RDBMS and not NoSQL databases?

**Comment by Ladicek** [comment]
The word "backend" seems quite overloaded to me. Maybe I'd use just "SQL Database", but I guess "Database Backend" is good as well.

**Comment by inoxx03** [comment]
@Ladicek How about "Relational Database" (or "Relational Database Backend" if we want to be more explicit)?

**Comment by Ladicek** [comment]
I have my personal opinions about the word "relational", but to the rest of the world, SQL == relational, so "Relational Database [Backend]" is OK as well.

**Comment by SlavoKrupa** [comment]
I think that **Backend** word is critical. Otherwise, it suggests a database without application connected to that database.

**Comment by Ladicek** [comment]
Fine with me (but I still think the word backend is quite overloaded :-) ).

**Comment by inoxx03** [comment]
OK, "Relational Database Backend" it is, then. Thanks, guys:)

**Comment by inoxx03** [comment]
Fixed in PR #263 .

**Comment by inoxx03** [comment]
PR merged, closing this issue now.
