### ISSUE TITLE
Move generated documentation to /docs

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#173]
Root should be community of practice home; standalone HTML page will suffice for now.

**Comment by ALRubinger** [comment]
Assigning to @rhoads-zach; my first commit does most of the work aside from updating the links in the generated docs to have root of "/docs/"

**Comment by ALRubinger** [comment]
Note: upon this getting upstream we'll have to update READMEs in the Booster repos which point directly to their documentation to update the link to reference the new "/docs" location.  Also once this is up, we can work on the root community of practice landing page, currently stubbed out in my commit 72aa740

**Comment by ALRubinger** [comment]
![screenshot15](https://cloud.githubusercontent.com/assets/199891/25370656/2e0a44e4-295a-11e7-9659-9fe6ef162d78.png)

Image of temp root landing page.  Why yes, I did use the `<MARQUEE>` tag.

**Comment by rhoads-zach** [comment]
@ALRubinger updated here: https://github.com/ALRubinger/appdev-documentation/pull/1
