### ISSUE TITLE
Fix display issues in footer when window is not wide enough

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#174]
....and it needs to be pretty wide :)
![screenshot14](https://cloud.githubusercontent.com/assets/199891/25370592/d52a837a-2959-11e7-9fb1-dcad7c127e10.png)

**Comment by edewit** [comment]
hmm... somebody added `File a Documention Bug` into the links let's see if we can but the license above the links

**Comment by rhoads-zach** [comment]
@edewit i added "file a bug" as per some feedback from a meeting with @ALRubinger 

@edewit @ALRubinger I don't think we agreed on the text for the link so if you two want something different, feel free to change it @edewit

**Comment by rhoads-zach** [comment]
@edewit also, see this update in @ALRubinger repo:
https://github.com/ALRubinger/appdev-documentation/pull/1/commits/8900201ae6173318fcf915a052df0ed5b67d8689

We're moving docs to be hosted under /docs/* so i rippled those changes to 6 lines in your CSS. Please let take a look and let me know if i missed something.

**Comment by edewit** [comment]
https://github.com/ALRubinger/appdev-documentation/pull/1/commits/8900201ae6173318fcf915a052df0ed5b67d8689 seems fine

I have a a change pending where I put the image and the licence next to each other above the links,  like this:
![screenshot from 2017-04-25 16-37-28](https://cloud.githubusercontent.com/assets/51133/25391037/8911da48-29d5-11e7-99ea-d893ac712030.png)

**Comment by edewit** [comment]
@rhoads-zach if you like I can make a PR for this change

**Comment by rhoads-zach** [comment]
@edewit sure go ahead and do the PR. I'll merge it and rebase update my PR to @ALRubinger
