### ISSUE TITLE
Launchpad automated script issues

### ISSUE THREAD

**Issue by SlavoKrupa** [openshiftio/appdev-documentation#175]
* Docs should point to released version (not master)
* Script does not work in current master branch

**Comment by rhoads-zach** [comment]
i can do the first bullet

@cmoulliard can you look at the second?

**Comment by rhoads-zach** [comment]
@SlavoKrupa mind reviewing linked PR?

**Comment by rhoads-zach** [comment]
Merged the link update.

@cmoulliard mind taking  a look at the script issue?

**Comment by Ladicek** [comment]
I was thinking, maybe the script in the `master` branch should always point to the `master` template, and the script in the `production` branch should point to the latest released template? But that would probably require error-prone manual work when merging to the `production` branch...

**Comment by SlavoKrupa** [comment]
Make sense :) If we can do it without manual steps it would be even better...

**Comment by cmoulliard** [comment]
What is the problem as you can pass[ the version](https://github.com/openshiftio/appdev-documentation/blob/master/scripts/deploy_launchpad_mission.sh#L61) to be used ?

**Comment by Ladicek** [comment]
There's no _problem_ per se. I was just thinking it would be more friendly.

**Comment by cmoulliard** [comment]
> would be more friendly.

To do what ?

**Comment by Ladicek** [comment]
To deploy the intended Launchpad version? When looking on the docs stage, I probably want to deploy the latest Launchpad as well, and when looking on the released docs, I want to deploy the released Launchpad.

Anyway, I realize this is offtopic to the original issue. Probably should have never started with this idea :-)

**Comment by rhoads-zach** [comment]
@cmoulliard @Ladicek @SlavoKrupa 

Current script uses "V4" which fails by default. Does this need to be changed?

**Comment by Ladicek** [comment]
`v4` will be released on Friday I think, but for now, indeed it fails.

**Comment by gastaldi** [comment]
A suggestion would be to use `next` instead (see @ALRubinger email)

**Comment by cmoulliard** [comment]
ou can pass the version to be used as defined here --> https://github.com/openshiftio/appdev-documentation/blob/master/scripts/deploy_launchpad_mission.sh#L11

**Comment by SlavoKrupa** [comment]
Original purpose of the issue was about failure of the script even with correctly defined version:
```
error: DeploymentConfig "launchpad-missioncontrol" is invalid: spec.template.metadata.labels: Invalid value: {"app":"launchpad","deploymentconfig":"launchpad-missioncontrol"}: `selector` does not match template `labels`
```

Then I found out that I was using older version of `oc` client (1.3..) which brought to my attention that we do not have anywhere documented which version of `oc` client should developers use?

IIRC it was originally mentioned in the boosters readme.
@rhoads-zach Do you know whether it is mentioned somewhere or is it missing ?

**Comment by SlavoKrupa** [comment]
And one more thing about the script:
`Replace edit role with admin in order to allow the jenkins serviceaccount to by example create rolebindings, ...`
 @cmoulliard is this still necessary ? Or shall I create new issue for this?

**Comment by rhoads-zach** [comment]
@SlavoKrupa mind taking a look at #207?

**Comment by rhoads-zach** [comment]
@SlavoKrupa We have a clear callout about the correct `oc` version in the docs:
http://appdev-stage.openshift.io/docs/minishift-installation.html#_prerequisite_install_a_single_node_openshift_cluster

Closing for now. Please re-open if theres more work to be done on this.
