### ISSUE TITLE
Fix deploy postgresql database in Getting Started Guide 

### ISSUE THREAD

**Issue by spisiakm** [openshiftio/appdev-documentation#177]
There's a note in section 2.1. Use the Launchpad to Launch a Booster saying that if I am launching the CRUD mission through continuous delivery, I have to deploy the Postgres database before launching my mission. This is wrong as I have to deploy the Postgresql database manually only when not using continuous delivery option in Launchpad. When using continuous delivery, Postgresql database deployment is defined in Jenkinsfile.

**Comment by rhoads-zach** [comment]
Thank you for the feedback @spisiakm 

This has been fixed and merged in this pr:
https://github.com/openshiftio/appdev-documentation/pull/165

and can be seen here:
http://appdev.openshift.io/getting-started.html#launchpad-launch-booster-cd
