### ISSUE TITLE
weird behavior of code snippets when mouse over

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/appdev-documentation#187]
I'm looking at http://appdev-stage.openshift.io/docs/getting-started.html, chapter _2.3.1. Update Using Continuous Delivery_. I see that item _1. Clone your project from GitHub_ has a shell snippet that I can copy and paste, so I try to select the snippet by mouse... but when I move the cursor over the snippet, the word `ruby` appears at the beginning of the line. This happens for a lot of other snippets as well. This happens both in Firefox 53.0 and Chrome 58.0.

**Comment by rhoads-zach** [comment]
I believe this is related to language specified in the source block and the behavior of the syntax highlighter. It seems like it defaults to ruby if no language is specified. I'll try and get to this later today.

**Comment by Ladicek** [comment]
Oh, one clarification: I don't really care what word appears on the beginning of the line. `ruby` certainly looks weird for a shell script, but I'd very much prefer if it didn't happen at all. Sorry if that was obvious, I figured I'd rather clarify :-)
