### ISSUE TITLE
REST Level 0 or API Level 0 ... you decide

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#220]
Ok, we need to decide whether the mission will be called "REST Level 0" or "API Level 0" as there is inconsistency between launch.openshift.io and the documentation as well as within the documentation itself.  You can search on either title and find results in the docs repo.

**Comment by Ladicek** [comment]
"API Level 0" doesn't make sense to me, the term "API" is way broader than just RESTful APIs. The linked commit seems to use "REST API Level 0" which I wholeheartedly agree with.
