### ISSUE TITLE
Document messages from Health Check

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#222]
![hc messages](https://cloud.githubusercontent.com/assets/367748/25762577/8156c8c6-319c-11e7-8bf1-8bc1bb55afb1.png)

That attached image shows the messages generated in OpenShift when the "Kill Me" button is pushed in the Health Check mission.  It may be useful to document these as expected.

**Comment by inoxx03** [comment]
additional enhancements in PR #232
