### ISSUE TITLE
Installation on CDK

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#226]
Just as we have "Installation on Minishift", we'll need "Installation on CDK".  There will be a lot of overlap, but some important differences, so the chunked content approach will likely help us a lot here.

@ALRubinger can adapt instructions from https://developers.redhat.com/blog/2017/02/28/using-red-hat-container-development-kit-3-beta/ to make this work if we get the scaffolding for the new doc set up.

**Comment by cmoulliard** [comment]
@ALRubinger We could mention within the doc that CDK includes :  
- The Centos/RHEL iso image used to create the VM, 
- The OpenShift oc client
BUT it requires a Red Hat subscription (still need to figure out the benefit)

**Comment by ALRubinger** [comment]
@cmoulliard The subscription is a 0-cost one through the Developer Program, but still needs to be specified in `--username` and `--password` flags on CDK boot (`minishift start`)

**Comment by rhoads-zach** [comment]
@inoxx03 i'll take this on my plate.

**Comment by inoxx03** [comment]
@rhoads-zach np, Thanks:)
