### ISSUE TITLE
Update the implementation status of Missions on wiki title page

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#235]
The implementation status for some of the missions on the [Wiki title page](https://github.com/openshiftio/appdev-documentation/wiki) is out of date and needs to be updated.

**Comment by rhoads-zach** [comment]
@inoxx03 are you still working on this or can it be closed?

**Comment by inoxx03** [comment]
@rhoads-zach I updated the Wiki title page  to include the Circuit Breaker, Documentation Site and Secured SSO Missions.
I'll close this issue now

[https://github.com/openshiftio/appdev-documentation/wiki](Wiki Title Page)
