### ISSUE TITLE
Normalize the format of the Secured SSO Booster Guides

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#236]
The documentation for Secured SSO Boosters has different formatting compared to the rest of the booster guides. We should clean up the formatting so that it fits in  stylistically with the remaining guides.

**Comment by inoxx03** [comment]
@starksm64 What is the current status of the Secured SSO booster? I'd like to update the Booster status info on the Wiki page.

**Comment by rhoads-zach** [comment]
fixed here: https://github.com/openshiftio/appdev-documentation/pull/255
