### ISSUE TITLE
Create Contribution Guide for Documentation

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#239]
Should contain all information needed to bootstrap internal and external contributors to:

launch.openshift.io development
Filing issues
Filing documentation issues
Links to upstream runtime project development

**Comment by ALRubinger** [comment]
First sending to @rhoads-zach for some scaffolding, then I can take over and we can all put into it :)

**Comment by rhoads-zach** [comment]
@ALRubinger consider how you would like to differentiate it with the contributing section here:
https://github.com/openshiftio/appdev-documentation/blob/master/README.adoc

**Comment by rhoads-zach** [comment]
@ALRubinger scaffolding is done so re-assiging to you.

**Comment by tradej** [comment]
I am taking this issue. We have agreed with @ALRubinger that I'll first provide the contribution instructions for the documentation alone. When that is done, I'll start working on a guide that explains how to contribute your own boosters.

**Comment by rhoads-zach** [comment]
@tradej take a look at README.adoc for the initial instructions for contributing to the docs. Once this is up, we should also discuss how we want to maintain our README

**Comment by tradej** [comment]
@rhoads-zach Will do. I absolutely think README should be assembled from the same modules the larger Contrib Guide will be built from.

**Comment by rhoads-zach** [comment]
@tradej nice work on #365 

I think it adds some nice content to this guide.

One more task that is a part of this issue:

Figure out how this gets linked on the landing page: https://github.com/openshiftio/appdev-documentation/blob/master/docs/landing-page/master.adoc

**Comment by tradej** [comment]
@rhoads-zach Re README: I have done some digging, and there is a big problem with the README—GitHub [apparently](http://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know/#3-swap-an-include-for-a-link) renders AsciiDoc files in the _SECURE_ mode, which means all the _include_ directives are disabled.

At the moment, I can't see a way of single-sourcing the README file from anywhere else, so my suggestion is to use README as a sort of hub linking to various other documents and containing only basic information.

WDYT?

**Comment by rhoads-zach** [comment]
@tradej this is main README file for this repo, correct? If thats the case then i'm fine with that approach.

**Comment by tradej** [comment]
@rhoads-zach It is. Thank you.

**Comment by tradej** [comment]
I will update the README file once the Contribution Guide is published somewhere. (see #413)

**Comment by tradej** [comment]
Closing as the CG is published and referenced from the README.
