### ISSUE TITLE
Docs should not have per-platform notes

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#24]
Just as we handle a guide per runtime (Vert.x, Swarm, Boot) in the Boosters, installation instructions should be per platform (Windows, Mac, *nix) so user's don't have to comb through irrelevant pieces.  So, starting with the Launchpad on Minishift installation guide, we'll need to extract platform-specific stuff into includes and have the build select the right one to make guide-per-platform.

**Comment by inoxx03** [comment]
@ALRubinger Maybe we could point users to the (Red Hat Development Suite)[https://developers.redhat.com/products/devsuite/overview/] installer.

**Comment by rhoads-zach** [comment]
@inoxx03 and @ALRubinger 

We do have this:
http://appdev-stage.openshift.io/docs/minishift-installation.html#_install_the_red_hat_container_development_kit

**Comment by rhoads-zach** [comment]
Since we link off the the install guides which do separate by platform, i'm closing this.

FYI @ALRubinger @inoxx03
