### ISSUE TITLE
Create Guide: Breaking Down the Boosters

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#240]
Explain, in the context of an example Booster, what is being set up for a user (so they might manually create a project on their own)

* pom.xml elements
* Relevant application code
* fabric8-maven-plugin config

**Comment by Ladicek** [comment]
I think we should have this for users to understand the booster structure, how it works. But I don't think we should expect users to deconstruct a booster in order to start from scratch.

**Comment by rdruss** [comment]
I agree​ with with Ladislav.  The explanation of the booster components is important but does not fill the "from scratch" need.

**Comment by rhoads-zach** [comment]
@Ladicek @rdruss @ALRubinger 

Re: "from scratch" we have this section in each dev guide: http://appdev-stage.openshift.io/docs/wf-swarm-runtime.html#_creating_an_application_from_scratch

Do you feel like it makes sense to document the specific pom of each booster and do a "from scratch" explanation? Or just one of the two?

**Comment by Ladicek** [comment]
Personally, I think "creating an application from scratch" is more important than "breaking down a booster". I guess we want to have both, but if I personally had to choose one of the two, I'd choose "creating an application from scratch".
