### ISSUE TITLE
Document: The Developer Journey

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#243]
Write up our value-add!

The general story arc takes a new developer from nothing into CD, with explanations behind:
* Building and deploying locally on host
* Building locally on host, baking and deploying on local cloud
* Building and deploying on OSO

Should be told as a story in easily-consumable manner - the website version of a conference talk

RHT internal reference: https://issues.jboss.org/browse/OBST-240

**Comment by rdruss** [comment]
How about debugging and testing to complete the story?

**Comment by ALRubinger** [comment]
@rdruss Definitely.  Unfortunately we don't yet have the tech to support testing in the running OS environment yet.  That's under dev alongside the ARQ team.

**Comment by rdruss** [comment]
@ALRubinger what about how we are currently testing the boosters?  Is the plan to release 1.0.0.GA without a recommendation for testing?

**Comment by ALRubinger** [comment]
@rdruss IMO it'd be a shame if we were somehow forced to do that, or release hacks.  Some teams are still bullish on the OpenShiftTestAssistant, and I'm still holding out that we continue to align with ARQ.

**Comment by rhoads-zach** [comment]
@ALRubinger @rdruss 

Do you want this "from scratch" or using an existing booster/mission?

If you want this "from scratch" then #240 is a blocker.

**Comment by Ladicek** [comment]
I'm not sure I understand this correctly, but IMHO, this could be based on one of the boosters (preferrably the least complex one).

**Comment by rhoads-zach** [comment]
@Ladicek @ALRubinger @rdruss 

My first pass at addressing this can be seen here:
http://appdev-stage.openshift.io/docs/getting-started.html

Let me know what you think.

**Comment by Ladicek** [comment]
I only took a cursory look, but it looks good! Two ideas:

- One can also do the CI/CD flow on local Minishift, which allows for easier experimenting.
- The text doesn't really describe how the CI/CD flow works under the hood. It probably doesn't belong to this guide, but we should have a description somewhere. Maybe a link to OpenShift docs, if we think this isn't appropriate to RHOAR docs, but I guess that we want to have a short chapter on this (the our opinion on how to do CI/CD).

**Comment by rhoads-zach** [comment]
@Ladicek thank you for the feedback, moving second bullet to its own issue: #283

**Comment by rhoads-zach** [comment]
@Ladicek @jclingan Updated with your feedback in #284
