### ISSUE TITLE
Missing missions - Appendices

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#252]
It looks like that some missions (ConfigMap for all the runtimes) are missing within the appendices of the doc

![screenshot 2017-06-01 09 25 22](https://cloud.githubusercontent.com/assets/463790/26668997/78270142-46ac-11e7-83d7-2666110cda01.png)

**Comment by inoxx03** [comment]
@cmoulliard @rhoads-zach It seems that this is no longer an issue now that we have per-runtime Developer Guides instead of a common Getting Started Guide. Closing.

**Comment by inoxx03** [comment]
My mistake, I see that the appendix section has been retained for now. Reopening. Going to updated the section and file a PR

**Comment by inoxx03** [comment]
fixed in PR #273
