### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by kenfinnigan** [openshiftio/appdev-documentation#26]
As we begin to add more content into /docs/topics I'm wondering whether we need to arrange the files into sub directories related to the specific topic?

As we get more and more chunked content all in /docs/topics it will become increasingly more difficult to locate the specific file you need to work with, look at, etc

**Comment by rhoads-zach** [comment]
@kenfinnigan adding directories around topic subject may make it easier to find certain pieces of content, but it introduces an additional management/maintenance task to keep the taxonomy up to date.

Do you have a specific structure in mind or an idea around organization?

**Comment by kenfinnigan** [comment]
unfortunately not.

I think my thoughts were around making it easier to view content within the github repo without having to build it.

Maybe it won't be an issue once we have CI build process for docs to boosters, etc

**Comment by kenfinnigan** [comment]
closing as we've now got the docs being generated which makes it easier to see
