### ISSUE TITLE
Asciidoctor typo error - manual install minishift and nexus

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#268]
The nexus install manual contains an asciidoctor syntax error 

<img width="1356" alt="screenshot 2017-06-09 06 44 39" src="https://user-images.githubusercontent.com/463790/26961476-3bf62282-4cdf-11e7-90e2-4d2dc7d873da.png">

**Comment by inoxx03** [comment]
@cmoulliard Thanks fore catching this:)  Fixed in PR #270

**Comment by inoxx03** [comment]
PR merged, closing this issue now.
