### ISSUE TITLE
Booster README.md files should not use "http" tool

### ISSUE THREAD

**Issue by balunasj** [openshiftio/appdev-documentation#27]
User feedback - user had no idea what the "http(ie)" tool is. We should replace references to the http tool with text to "load this URL in your browser". Usage of curl in the README.md is acceptable since it is a well-known tool. "For unix/linux users, curl ..."

**Comment by rhoads-zach** [comment]
@balunasj we use CURL and browser interaction in the current HTTP Level 0:

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-basic-interaction-spring-boot-tomcat.adoc

Is this acceptable, or do we need to move to only browser?

**Comment by rhoads-zach** [comment]
@balunasj i wanted to follow up on this issue. Is curl fine or should we move to browser only?

**Comment by balunasj** [comment]
@rhoads-zach Curl is a good, I would not want to move to browser only.  If it is both that is ok, but not required atm.

**Comment by rhoads-zach** [comment]
Thanks @balunasj. We have curl and browser in the HTTP API example so i'll close this issue.
