### ISSUE TITLE
Describe Build and Deploy process in more detail

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#283]
GSG doesn't really describe how the CI/CD flow works under the hood. It probably doesn't belong to this guide, but we should have a description somewhere. Maybe a link to OpenShift docs, if we think this isn't appropriate to RHOAR docs, but I guess that we want to have a short chapter on this (our opinion on how to do CI/CD).

**Comment by Ladicek** [comment]
I'm looking at it again and the first paragraph at http://appdev-stage.openshift.io/docs/getting-started.html#_continuous_delivery_using_openshift_online actually contains most of it. Maybe we could mention that:
- as part of the OSO deployment, we'll also create a pipeline build
- this pipeline build uses the `Jenkinsfile` from the booster
- this `Jenkinsfile` contains the deployment "recipe"
- and the webhook just triggers a new pipeline build

I think that would be enough.

**Comment by rhoads-zach** [comment]
@lavernw1 or @tradej 

Do either one of you want to grab this off my plate?

**Comment by lavernw1** [comment]
Sure, we can discuss after meeting tomorrow. Is a new section required or just update continuous delivery topic in section 6

**Comment by inoxx03** [comment]
@lwithers If I may follow up on your question: I think it could either be a new shorter separate section, or a description paragraph that will be added  Section 6 of the GSG. Ether way, it might be a good idea to put it in a separate topic file so we can include it anywhere.

**Comment by lavernw1** [comment]
Thanks for the updates. Appreciate it.

**Comment by rhoads-zach** [comment]
FYI please incorporate any updates from above issue into this doc work

**Comment by lavernw1** [comment]
@Ladicek I'm looking to incorporate changes related to Planning issue #35 Support fabric8 jenkinsfile library for this task to describe CI/CD  for the Getting Started Guide.  I looked at the #35 planning issue and the discussion of pre-defined patterns (blue-green, etc) and fabric8 links. Can you give me idea of what I would need to emphasize for Fabric8 jenkinsfile flows in our general CI/CD topic.

**Comment by Ladicek** [comment]
@lavernw1 Sorry, I don't have the details just yet, as that work is yet to be done. I also don't think this should affect RHOAR docs, that's specific to OpenShift.io -- but maybe @rhoads-zach or @ALRubinger have a different opinion?

**Comment by lavernw1** [comment]
@Ladicek  thanks for the update. @ALRubinger can you refer me to any resources or have ideas related what whould be good to include in our CI/CD topic as it relates to the Jenkinfile libray in fabric8.

**Comment by rhoads-zach** [comment]
@lavernw1 the process has been updated to directly use s2i:

https://appdev.prod-preview.openshift.io/docs/getting-started.html#build-and-deploy-process

@Ladicek @ALRubinger do you think we need to go into a deeper explanation?

**Comment by Ladicek** [comment]
I think it's fine.

**Comment by rhoads-zach** [comment]
thank you @Ladicek closing for now.
