### ISSUE TITLE
Security review advises against using UltraHook

### ISSUE THREAD

**Issue by quintesse** [openshiftio/appdev-documentation#294]
See https://docs.google.com/document/d/1PA8y9sLddKbyYgabK2l0Fjx3dGaf3l-HlTHR_vX3MRo

Do we care about this given the fact that this isn't supposed to be used in production environments?

**Comment by Ladicek** [comment]
Is there an alternative that would be OK from PST perspective? I don't know, but quick googling revealed at least https://ngrok.com/

**Comment by gastaldi** [comment]
@Ladicek I don't think that changing to ngrok would make any difference, given that ultrahook also supports HTTPS URLs. Perhaps a solution in this case would be to poll instead

**Comment by rhoads-zach** [comment]
@quintesse @Ladicek @gastaldi 

take a look at #295. I removed references to ultrabook in the docs to address this issue. If you prefer a different approach, let me know.

**Comment by quintesse** [comment]
So that comes down to removing Ultrahook in favor of just manually triggering changes yourself, right @rhoads-zach ?

**Comment by rhoads-zach** [comment]
@quintesse that is what implemented in the docs since ultrabook was an "optional" step. I kept the content so we can re-add later if necessary.
