### ISSUE TITLE
Second pass at POM breakdown sections

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#296]
I took the first pass at the POM breakdown sections in the runtime guides:

http://appdev-stage.openshift.io/docs/wf-swarm-runtime.html#breakdown_pom
http://appdev-stage.openshift.io/docs/vertx-runtime.html#breakdown_pom
http://appdev-stage.openshift.io/docs/spring-boot-runtime.html#breakdown_pom

@inoxx03 would you mind taking a second pass at it?

**Comment by inoxx03** [comment]
@rhoads-zach no problem, assigning this issue to myself:)
