### ISSUE TITLE
Add Testing to doc builds

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#297]

**Comment by tradej** [comment]
I have a few ideas that I will need to go over, but I am reasonably sure we can come up with a meaningful test suite with the existing infrastructure.

**Comment by tradej** [comment]
Note to self: OpenShift documentation uses AsciiBinder

**Comment by tradej** [comment]
Note to self: We only want to build all our books the standard way, see if _xmllint_ passes. Previewing builds is an extra.

**Comment by tradej** [comment]
Apparently, the rest of the team uses ci.centos.org. Investigation needed.
