### ISSUE TITLE
Add additional resources to Swarm Runtime Guide

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#303]
Add this:
https://github.com/wildfly-swarm/wildfly-swarm-presentations

@kenfinnigan @heiko-braun any other materials you can think of to add here:
http://appdev-stage.openshift.io/docs/wf-swarm-runtime.html#wf-swarm-additional-resources

**Comment by rhoads-zach** [comment]
also found this:
https://github.com/redhat-microservices/lab_swarm-openshift

**Comment by kenfinnigan** [comment]
That's all we have
