### ISSUE TITLE
Add additional resources to SpringBoot Runtime Guide

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#305]
Add this to the resources for a SpringBoot Runtime Guide:
https://github.com/redhat-microservices/lab_springboot-openshift

@cmoulliard any other items to add to this section:
http://appdev-stage.openshift.io/docs/spring-boot-runtime.html#sb-tomcat-additional-resources

**Comment by gytis** [comment]
Links to Spring Boot and FMP docs might be useful.

**Comment by metacosm** [comment]
https://docs.openshift.org/latest/architecture/index.html might be useful for beginners.
