### ISSUE TITLE
Add legacy url redirects after runtime guide refactor

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#306]
Add redirects for old URLs generated in boosters.

For example:

http://appdev.openshift.io/docs/mission-http-api-vertx.html

to 

http://appdev.openshift.io/docs/vertx-runtime.html#mission-http-api-vertx

**Comment by tradej** [comment]
My current progress is in [my repository](https://github.com/tradej/appdev-documentation/tree/issue-306). I'm putting this away for a while because it's really frustrating to get the tests working.

**Comment by tradej** [comment]
Note to self: The app has been moved to Nginx, so the setting is in `$REPO_HOME/nginx.conf`. Testing should probably be configured in the CI file.
