### ISSUE TITLE
[Spring Boot Tomcat Runtime Guide] Appendix B

### ISSUE THREAD

**Issue by RadekKoubsky** [openshiftio/appdev-documentation#307]
Looking at number 8 in [Appendix B](http://appdev-stage.openshift.io/docs/spring-boot-runtime.html#breakdown_pom):
`This Maven goal is part of the Spring Boot Tomcat Maven plugin and will repackage the existing jar file that is created during the package goal.`

Actually, the goal is part of `spring-boot-maven-plugin` not Spring Boot Tomcat Maven plugin. In addition, we can explain why is the `repackage` goal there, as stated in the [plugin docs](https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html):
`Repackages existing JAR and WAR archives so that they can be executed from the command line using java -jar.`

**Comment by inoxx03** [comment]
Thanks @RadekKoubsky. I'll include this information when as part of resolving #296.

**Comment by inoxx03** [comment]
Resolved in PR #315
