### ISSUE TITLE
Create a Glossary

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#309]
There may be developers reading our docs who are not familiar with some terms that we use, such as _opinionated framework, continuous delivery pipeline,_ or _reactive systems._

We should create a glossary that would explain such terms based on the expected knowledge level of the target audience. 

This glossary should be shared across the whole doc set.

*Possible sub-task: Get better description of the target audience from the stakeholders.*

**Comment by tradej** [comment]
Note to self: Update the dept. technical glossary as well.

**Comment by Ladicek** [comment]
Related: some terms are generic ("opinionated framework", "continuous delivery") and some terms are only related to our metaphor of launching rockets to space ("booster", "mission"). We should make sure that noone confuses our metaphor with generic industry terms.
