### ISSUE TITLE
appdev-documentation/docs/minishift-installation/topics directory is a bad link

### ISSUE THREAD

**Issue by starksm64** [openshiftio/appdev-documentation#31]
None of the references in the appdev-documentation/docs/minishift-installation/master.adoc doc into the topic subdirectory are resolving because this appears to be an invalid link.

**Comment by ALRubinger** [comment]
@starksm64 The link is good, but GitHub isn't rendering it right.

Pulling down the docs repo and running the build per instructions in the README here should get you properly generated docs.  And then you can get at 'em like `file:///home/alr/business/jboss/git/openshiftio/appdev-documentation/html/minishift-installation.html`

FYI I'm right now working on a CI job to gen docs for us publicly.

**Comment by starksm64** [comment]
Ah, ok. I am able to generate them locally and view them.

**Comment by rhoads-zach** [comment]
Thanks @ALRubinger. Closing this issue.
