### ISSUE TITLE
take an editing pass at front-end content

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#314]
review and edit topics used for display on the front end.

Currently topics created here:
#313 
#308 

Will continue to update this issue as new PRs are added.

**Comment by rhoads-zach** [comment]
FYI @edewit can you add your PRs to this list as you create new topics so we can track what needs a second editing pass?

**Comment by edewit** [comment]
Those 2 now listed come from the boosters, index.html we are going to have a process in place to merge these with the code and create PRs automatically.
