### ISSUE TITLE
fix nested topics/topics folder

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#32]
The following topic is nested in topics/topics:

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/topics/OBST-wf-swarm-crud-deploy-to-openshift-pipeline.adoc

move this file to be in the same dir as the other topics and fix any affected includes.

**Comment by inoxx03** [comment]
fixed in: https://github.com/openshiftio/appdev-documentation/pull/48
