### ISSUE TITLE
Add a Required infrastructure Component Versions Section to the Release Notes.

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#325]
IMHO it would be helpful if we included a common resource prerequisites topic with our docs, as it would provide a one-stop section that RHOAR users can reference to check whether they have the right version of JDK and Maven installed before they even start using RHOAR and the Launcher.

I know we used to have a section like that I an ancient version version of our docs, so I'm attaching a screenshot of the (severely outdated) table for reference:
![common_prereqs](https://user-images.githubusercontent.com/17914654/27792782-980818a8-5ffb-11e7-9f61-b275b81f2484.png)

EDIT:  we could also have a separate page for it outside of the docs (on CP or Mojo, maybe), but IMHO we definitely should keep track of the required versions of essential tools somewhere.

WDYT?

**Comment by tradej** [comment]
+1

**Comment by inoxx03** [comment]
Moving this to the next release after 2017-8-14. Removing this issue from Current Development for now.

**Comment by inoxx03** [comment]
Relates to JIRA [OBST-362](https://issues.jboss.org/browse/OBST-362)

**Comment by inoxx03** [comment]
Required Component versions will be tracked in the Release Notes
