### ISSUE TITLE
Documentation sync

### ISSUE THREAD

**Issue by edewit** [openshiftio/appdev-documentation#326]
We've created a process that can update ( by creating PR's on the effected boosters ) all we need is adding this as a webhook on PR's. The address of the deployed service is:
```
http://doc-booster-synchronizer-doc-sync.e8ca.engint.openshiftapps.com/api/hook
```

**Comment by rhoads-zach** [comment]
@edewit added here:
https://github.com/openshiftio/appdev-documentation/settings/hooks/14756617

How do i test it?

**Comment by gastaldi** [comment]
@rhoads-zach change `docs/topics/rest-level-0-mission-intro-paragraph.adoc` and if that works we should see a PR in the rest-http boosters

**Comment by rhoads-zach** [comment]
@edewit and @gastaldi:

closing since i think the auto-pr-creation is working
