### ISSUE TITLE
Tag commit when pushing to production

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#328]
I suggest we use tag the last commit on the `production` branch every time we push the docs into production.

In my previous teams, we would always tag the commit that the production deployment was based on for reference. It came handy on a few occasions, namely when we needed to rollback to the previous 
working state, or when we wanted to checkout a specific file from the last deployment.

WDYT?

**Comment by Ladicek** [comment]
For QE reasons, I added the Git revision number to the rendered docs form. That's somewhat problematic because of #288, but I'd very much like to keep that. If we had human-readable tags, we could instead use the tag names for the version string, which would be nice and eliminate #288 (I think).

**Comment by tradej** [comment]
@Ladicek Are you solving the same problem, though?

You add the revision number during the build, but once the production environment is overwritten, there is no easy way to find out what the previous build was, or is there?

**Comment by Ladicek** [comment]
No, it's not a solution for the same problem, but it's a nice complement. I probably wanted to say -- I'm in favor of this idea, and I'd immediately use the tags as version numbers.

**Comment by tradej** [comment]
Oh, I see, I misunderstood. Yes, we can absolutely use these solutions in tandem. Let's wait for @rhoads-zach's opinion.

**Comment by rhoads-zach** [comment]
@tradej so this tag would exist in this repo and so we could essentially see every version we push to prod, correct?

**Comment by tradej** [comment]
@rhoads-zach Yes. I would say "...every version we *have pushed*...", but that's semantics. These are normal Git tags, so they're saved in `.git`, and work everywhere. `man git tag` has all the info. To view tags on GH, hit the  **Branch** button in the code view of the repo, and select the **Tags** tab (so far, we have none).

**Comment by rhoads-zach** [comment]
Sure, i'm fine with creating tags for our releases.

@ALRubinger do you have any feelings about tag format? 

my thoughts:
* 2017.07.10 - Release
* 2017.Release1
* v2017.x

Other ideas?

**Comment by tradej** [comment]
In BxMS, we have used `$VERSION_rel_$DATE` (ISO format) as we publish basically on any day we want, so for example the release of version 6.4 on Feb 17 was tagged `6.4_rel_2017-02-17`. This is also convenient for versioning the docs because we only use timestamps now, so both the Git tag and the timestamp in the docs point to the same day.

**Comment by Ladicek** [comment]
AFAIK we don't even have version numbers for RHOAR, or at least not public ones. Sure we could invent special versioning scheme just for documentation, but for me, anything human-readable would work. Even an ISO timestamp.

**Comment by tradej** [comment]
If that's the case, +1 to ISO timestamp.

**Comment by rhoads-zach** [comment]
So the current version of the docs does have _both_ a date and a GH hash (at the bottom):
http://appdev-stage.openshift.io/docs

Would you want to combine those to something like: `$HASH_rel_$DATE`.

e.g.: `0cec512f42_rel_2017-07-11`

**Comment by tradej** [comment]
If you're asking me, I think it's not necessary. You can easily search by commit hashes already, and the tag is there merely so that we have a pointer to the date.

Furthermore, if we decided later to use `$VERSION_rel_$DATE`, I can imagine having existing hash-based tags start with a number (that may be higher than the version) could break scripts if they used some form of version comparison.

All in all, I think ISO date like `2017-07-23` is sufficient for git tags.

P. S. To create today's tag easily, run `git tag $(date --rfc-3339=date)`

**Comment by rhoads-zach** [comment]
@tradej do you want this date tag _in addition to_ the "last updated" line at the bottom of the current docs?

**Comment by tradej** [comment]
I would say so, yes. The "Last updated" info in the docs is for readers, and the tag is for our team's tracking purposees. I could write a tiny script that would update the docs and create the tag at the same time if it's too bothersome.

**Comment by rhoads-zach** [comment]
ok @tradej that sounds good. Please forward with this solution and let me know if you need anything else.

**Comment by rhoads-zach** [comment]
Re-opening since the fix was rolled-back

**Comment by rhoads-zach** [comment]
@tradej i feel like this issue overlaps with #288, do you mind working with @Ladicek on that one too?

**Comment by tradej** [comment]
I certainly don't. I'll contact him right away.

**Comment by Ladicek** [comment]
IMHO, the tagging scheme as described in this issue and implemented in the script, is fairly human-readable and hence #288 is no longer an issue (from my POV).
