### ISSUE TITLE
Review and finalize HTTP API Level 0 intro, tradeoffs and resources

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#33]
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-intro.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-design-tradeoffs.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-resources.adoc

**Comment by rhoads-zach** [comment]
@starksm64 do you mind taking this?

**Comment by ALRubinger** [comment]
@starksm64 I'll take it.

**Comment by rhoads-zach** [comment]
@ALRubinger Closing this for now. Please re-open if you need any more updates.
