### ISSUE TITLE
Consider adding code owners to project

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#337]
https://github.com/blog/2392-introducing-code-owners

**Comment by tradej** [comment]
This is definitely an interesting idea, but the fact that we heavily reuse files makes this a tricky one.

**Comment by rhoads-zach** [comment]
I agree @tradej, its not straight forward. I was thinking we could try assign certain topics that are clearly associated with the runtimes and leave others unassigned or assign to a default member.

WDYT?
