### ISSUE TITLE
Is this wording appropriate "Single-node OpenShift Cluster" ?

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#339]
The documentation uses in many place `Single-node OpenShift Cluster` 

<img width="1002" alt="screenshot 2017-07-12 06 59 22" src="https://user-images.githubusercontent.com/463790/28102514-0243d074-66d0-11e7-82df-0c4514fc24f9.png">

Is the wording used appropriate ? For local or even remote instances, OpenShift is not deployed in a cluster mode anymore according to this description [1]. To avoid to confuse the developers, I would to suggest that we rephrase the text to `OpenShift platform`. 
As by default, openhshift or kubernetes are deployed in at least one node, this is also not required to mention it

[1] : https://docs.openshift.org/latest/install_config/install/planning.html

**Comment by rhoads-zach** [comment]
@cmoulliard this is the opening sentence from the Minishift docs[1]:

> Minishift is a tool that helps you run OpenShift locally by launching a single-node OpenShift cluster inside a virtual machine.


We chose `Single-note Openshift Cluster` as a generic term for running Minishift or the CDK on your local host. Do you still think its not appropriate? Would you prefer `Local Openshift Platform`? 

Basically, we're trying to convey that the users are deploying to an instance of OpenShift running on their machine as apposed to OpenShift Online.

[1]https://www.openshift.org/minishift/

**Comment by rhoads-zach** [comment]
@rkratky Let me know if you have any opinions on this.

**Comment by rkratky** [comment]
@rhoads-zach, I vote for '(single-node) OpenShift cluster' -- that would keep the terminology consistent with OpenShift (and CDK) docs.

**Comment by rhoads-zach** [comment]
per feedback from @rkratky, I think we should keep Single-node OpenShift cluster. @cmoulliard feel free to re-open if you'd like to discuss this more.
