### ISSUE TITLE
Redundant chapters for "Push Changes to ..."

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#340]
**1. Redundant chapters**

The following chapters are redundant :
- http://appdev-stage.openshift.io/docs/getting-started.html#_push_changes_to_a_single_node_openshift_cluster
- http://appdev-stage.openshift.io/docs/getting-started.html#_push_changes_to_openshift_online

The process to build/deploy a project using openshift running on your machine or in the cloud as they both require to be first logged and to have the rights to use a namespace/project.

I would like to suggest to merge the content the chapters into one where within the introduction part of the chapters you specify how to access to the instance locally, online. Excepted the hostname, the process to access openshift is also rigorously identical

**2. Rename to Deploy**

Push changes is not correct as the plugin f-m-p will do 2 things in order to install the application on the platform: 

- Generate the OpenShift/Kubernetes resources needed to setup; pod, service, route, buildConfig, deploymentConfig, ...
- Deploy the resources on the platform to install a pod running the application/runtime

This is why I suggest to rename "push changes" to "deploy".  

**3. Mistake under "4. Push Changes to OpenShift Online"**

This text displayed after the title is not correct as it should refer to the local installation
`You can also use the same process for pushing changes to a Single-node OpenShift Cluster with OpenShift Online.`

**4. Rephrase**

The message that we want to pass for the intro of the paragraph 3 should be improved as I don't see why a microservice is the first citizen choice for the cloud. The assertion can create confusion like also the fact that it can reduce problems that arise ....

`3. Push Changes to a Single-node OpenShift Cluster
Local development is a fine initial approach, but one of the big opportunities microservices presents is developing for the cloud first. This means pushing changes to the cloud and testing them as they are being developed. This can reduce problems that arise from "Well, it worked on my machine".`

I would prefer that we have a general intro chapter explaining the pros/cons to use Kubernetes or Openshift as deployment platform for our runtimes or microservices as the chapters 3/4 only refer to the process to deploy

**Comment by inoxx03** [comment]
>1. Redundant chapters

>The following chapters are redundant :

>http://appdev-stage.openshift.io/docs/getting-started.html#_push_changes_to_a_single_node_openshift_cluster
>http://appdev-stage.openshift.io/docs/getting-started.html#_push_changes_to_openshift_online

I agree that the overlap between the two chapters is sufficient to make them seem redundant in the current context. However, it might be a good idea to retain the redundant chapters for now, as we may be able to use them once we switch to user-story-driven documentation. That way, the user will be presented with a guide that will consist of topics that are relevant to his choice of environment.
WDYT?

**Comment by tradej** [comment]
To elaborate further on the point made by @inoxx03:

The trend in tech writing is to write documentation that can be read as a block from the top to the bottom without having to jump around in the document or, god forbid, open another book. This model is proving to be easier to read and preferred by readers.

Having said that, maintaining duplicate code in multiple files is to be avoided unless absolutely necessary, so the chapters should be single-sourced from one `adoc` file, and the relevant parts should be conditionalised using `ifdef` or replaced with attributes. Then, the inclusion directive in the book's source should be preceded by setting all the appropriate attributes so that the file renders properly.

**Comment by inoxx03** [comment]
@cmoulliard Thank you for the feedback. It appears that the issues you've pointed out in this ticket are related to the state of the Getting Started Guide prior to the refactor that was done last Friday. In the post-refactor state of the GSG, most of the cited passages have been removed, which renders your suggested changes no longer applicable.

In light of these new developments, I have two proposals:
1. Please check the post-refactor state of the [Getting Started Guide (Production version)](appdev.openshift.io/docs/getting-started.html) or the [latest staged version](appdev-stage.openshift.io/docs/getting-started.html). You are welcome to file an issues for any changes or fixes that you would like the Docs Team to make. 
2. I will close this ticket as 'wont fix' and the fixes will be made based on follow-up tickets.

**Comment by inoxx03** [comment]
Closing this as 'Won't Fix', proposed changes no longer applicable to the current state of docs.
