### ISSUE TITLE
Review and Finalize CRUD intro and resources

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#35]
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/crud-experience-intro.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/crud-experience-resources.adoc

**Comment by rhoads-zach** [comment]
@starksm64 do you mind taking this?

**Comment by heiko-braun** [comment]
@rhoads-zach looking at the most recent contents this seems to be fine. @cescoffier any comments as the owner of that mission?

**Comment by rhoads-zach** [comment]
@cescoffier do you mind taking this?

**Comment by cescoffier** [comment]
Fixed in #131
