### ISSUE TITLE
review and finalize intro and resources for configmap mission

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#37]
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-experience-intro.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-experience-resources.adoc

**Comment by rhoads-zach** [comment]
@starksm64 do you mind taking this?

**Comment by heiko-braun** [comment]
The relevant files are:

- https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-mission-intro.adoc
- https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-mission-resources.adoc

**Comment by rhoads-zach** [comment]
@cmoulliard mind taking this issue?

**Comment by heiko-braun** [comment]
@rhoads-zach looks good to me.

**Comment by rhoads-zach** [comment]
Thank you @heiko-braun closing this issue
