### ISSUE TITLE
Rework Intro paragraph in Getting Started

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#370]
The intro paragraph in the getting started guide could use a smoothing pass based on the updated content:
http://appdev-stage.openshift.io/docs/getting-started.html

Current topic is here: 
docs/topics/getting-started-intro.adoc

**Comment by rhoads-zach** [comment]
accidentally tagged wrong commit

**Comment by inoxx03** [comment]
I know but I noticed it too late. Sorry about that, my bad.

**Comment by inoxx03** [comment]
Draft in PR #388 

Suggestions welcome.
