### ISSUE TITLE
previewDocsServer.sh doesn't work in Fedora with SELinux on

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#378]
The `docker` invocations in `$REPO_HOME/scripts/previewDocsServer` do not work in Fedora if SELinux is on because it is blocking access to the user's directory. To solve this problem, Docker needs to be run in privileged mode by adding the `--privileged` flag.

Also, the script invocation needs to be done either using an account in the `docker` group (which is a security hole, and is discouraged), or as `root`. It should either be documented that the script should be run as `root` either using `sudo` or `su -c`, or the `docker` invocations should be prepended themselves.

Notes:
* If the whole script is run using `sudo`, the `$HOME` directory resolves to `/root`, which effectively means that all the Maven packages will be downloaded into root's `.m2` directory.
* If the `docker` invocations are prepended with `sudo`, it is not obvious to the user why root access is required.
* When using `pkexec` instead of sudo, each invocation of `docker` requires the user to enter the password separately, which results in inferior user experience.

**Comment by Ladicek** [comment]
If you _really_ want to do this, I'd recommend using `sudo` just for the `docker` invocations and linking to one of the many explanations, e.g. https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by tradej** [comment]
Yes, that seems like the most reasonable solution for me too. Since I believe we can expect the script's users to review and understand the code if they're spooked by the sudo prompt, I'll implement it like that.
