### ISSUE TITLE
Updated README templates to substitute using properties files instead of adoc

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#379]

**Comment by gastaldi** [comment]
@zrhoads1 you need to change the property pattern in the documents to be `${property}` instead of just `{property}`. Eg. `{localCmdRun}` becomes `${localCmdRun}`

**Comment by rhoads-zach** [comment]
@gastaldi updated branch, let me know if you have any other feedback

**Comment by rhoads-zach** [comment]
related to #380
