### ISSUE TITLE
Release tagging does not work on UNIX machines

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#392]
Following up on #391:

As reported by @rhoads-zach in the documentation Slack channel, the `$REPO_HOME/scripts/tagRelease.sh` script does not work on machines with OpenBSD or MacOS because the `date` binary there does not have the `--rfc-3339` flag. I assume this problem also affects the `ci/Jenkinsfile` script as I have used the same invocation there.

I believe the solution is to use `date "+%Y-%m-%d"` instead. I have verified it works on OpenBSD and Fedora. @rhoads-zach or someone with an Apple PC, can you please verify it works on MacOS as well?

**Comment by Ladicek** [comment]
I wonder if `date -I` (resp. `date --iso-8601`) would work? But I don't really mind, `date "+%Y-%m-%d"` will also work and is likely more portable.

**Comment by tradej** [comment]
Apparently, it will not. I have verified it on OpenBSD—none of the listed options is available there.
