### ISSUE TITLE
Track addressed issues

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#394]
Use some mechanic like Milestones to track issues addressed within a given time period (e. g. a sprint), and produce a changelog for each such period.

**Comment by tradej** [comment]
While the changelog generation could be automated, i believe that with the current number of issues solved per month, manually copying them from the solved issue list is sufficient at this point.

I have tried writing a simple Vim command to process the issue list and it seems very much feasible to me.

**Comment by tradej** [comment]
I have created a milestone called _Current Development._ When someone picks up an issue and starts working on it, they should add it to this milestone. Once we release, we rename Current Development to e. g. 2017-07-29 and create a new milestone called Current Development. Rinse and repeat.

**Comment by inoxx03** [comment]
@tradej Seems like an excellent solution to me:) Thanks for documenting it, too.

**Comment by tradej** [comment]
Milestones addressed in #406.

**Comment by inoxx03** [comment]
not really suitable for us right now, but still, not a bad idea: [keep-a-changelog](http://keepachangelog.com/en/1.0.0/)

**Comment by inoxx03** [comment]
CHANGELOG in PR #426
