### ISSUE TITLE
Review and finalize integration details with WF Swarm missions

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#41]
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-basic-interaction-wf-swarm.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/health-check-experience-basic-interaction-wf-swarm.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-experience-basic-interaction-wf-swarm.adoc

**Comment by rhoads-zach** [comment]
@heiko-braun mind taking this one?

**Comment by heiko-braun** [comment]
sure, i'll review it later on

**Comment by heiko-braun** [comment]
A few things:

- rest-level 0: the curl commands are wrong ad the payload changed. take a look here for the most recent examples: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http

- health-check: works completely different and is now aligned with the mission contents. take a look here: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-health-check

- configmap: minor changes to the pod names, etc. but overall reflects the contents more or less: See  https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-configmap

**Comment by heiko-braun** [comment]
@rhoads-zach this put's the ball back in your court

**Comment by rhoads-zach** [comment]
thank you @heiko-braun 

@kenfinnigan would you like to update this in the docs, or would you like us to?

**Comment by kenfinnigan** [comment]
If you're able to @rhoads-zach that would be awesome!

**Comment by rhoads-zach** [comment]
#91 and #90 help address some of the issues.

I'm still not clear on how to interact with the health check Mission. @kenfinnigan or @heiko-braun can you issue a PR updating the WF Health Check Mission on how you're supposed to interact with it?

**Comment by heiko-braun** [comment]
@rhoads-zach Sure, I can do that. But I am not clear what you expect. The basic interactions are described in https://docs.google.com/document/d/10ZzCVrxzifQeASAYlgFWERqgbYGj4ucJwCzpb37jTyw/edit#heading=h.we4w2qryfz43 and shared between all runtimes. What's the proper place to put common descriptions?

**Comment by heiko-braun** [comment]
@rhoads-zach I've update both the instructions for deployment as well interaction with booster: https://github.com/openshiftio/appdev-documentation/pull/92

Let me know if this is what you had in mind.

**Comment by heiko-braun** [comment]
Here's the fix to the basic http booster: https://github.com/openshiftio/appdev-documentation/pull/93

**Comment by heiko-braun** [comment]
Configmap seem to be fine

**Comment by heiko-braun** [comment]
Here are the changes so far:

- [x] healthcheck instructions: https://github.com/openshiftio/appdev-documentation/pull/96
- [x] basic http instructions: https://github.com/openshiftio/appdev-documentation/pull/93
- [x] crud instructions: https://github.com/openshiftio/appdev-documentation/pull/96
- [x] configmap instructions: no changes needed

**Comment by heiko-braun** [comment]
@starksm64 Do you take care of the secure-rest instructions at [1] ?

[1] https://github.com/openshiftio/appdev-documentation/tree/master/docs/mission-secured-wf-swarm

**Comment by starksm64** [comment]
Yes, they should be good but I will go over them again today.

**Comment by rhoads-zach** [comment]
@starksm64 if everything looks good do you mind closing this issue?

**Comment by starksm64** [comment]
I have gone through them and the are fine, but I don't have permission to close the issue.

**Comment by rhoads-zach** [comment]
thanks @starksm64 closing.
