### ISSUE TITLE
Change resource links to git repos in each booster

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#425]
Each booster has a "Resources" section with links to github repos. 

For example:
http://appdev-stage.openshift.io/docs/spring-boot-runtime.html#mission-http-api-spring-boot-tomcat

has:
REST API Level 0 Mission - Eclipse Vert.x Booster
REST API Level 0 Mission - WildFly Swarm Booster
REST API Level 0 Mission - Node.js Booster

Which points to github repos. Those links instead should point to the correct section in the runtime guides.

**Comment by inoxx03** [comment]
resolved in #429
