### ISSUE TITLE
Run Documentation in DevTools OSD

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/appdev-documentation#428]
This is not a blocker to public launch.openshift.io, but the repository needs some adjustments to be able to build in ci.centos.org and to be published in the Devtools OSD

We need the following files to exist in this repository (it can be copied/based on what's available in https://github.com/openshiftio/launchpad-frontend):

- `cico_build_deploy.sh`
- `Dockerfile.build`
- `Dockerfile.deploy`
- `openshift/template.yaml`

**Comment by tradej** [comment]
Hi, @gastaldi, what sort of building are we talking about in ci.centos.org? Building for production, nightlies, pull requests, or something yet different?

**Comment by gastaldi** [comment]
Basically building for the staging (everytime a push happens, the docs are
built and the image is redeployed) and providing means to update to
production.

Em 8 de ago de 2017 06:50, "Tomas Radej" <notifications@github.com>
escreveu:

Hi, @gastaldi <https://github.com/gastaldi>, what sort of building are we
talking about in ci.centos.org? Building for production, nightlies, pull
requests, or something yet different?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/appdev-documentation/issues/428#issuecomment-320908262>,
or mute the thread

**Comment by tradej** [comment]
Can this be closed now?

**Comment by gastaldi** [comment]
Yes, thanks for pointing that out
