### ISSUE TITLE
Review and finalize spring boot tomcat missions interaction

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#43]
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-basic-interaction-spring-boot-tomcat.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/health-check-experience-basic-interaction-spring-boot-tomcat.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-experience-basic-interaction-spring-boot-tomcat.adoc

**Comment by rhoads-zach** [comment]
@cmoulliard do you mind taking this one?

**Comment by cmoulliard** [comment]
> do you mind taking this one?

Yes Zach

**Comment by gytis** [comment]
I've modified HTTP, CRUD and ConfigMap app names and fixed HTTP booster endpoint: https://github.com/openshiftio/appdev-documentation/pull/75

**Comment by rhoads-zach** [comment]
Thank you @gytis.  #75 is now merged. The only outstanding one is Health Check

**Comment by gytis** [comment]
@rhoads-zach I left health check because the spec is not finalised yet. Will have to update the docs once the spec and implementation are complete.

**Comment by heiko-braun** [comment]
@gytis here are the health check instructions we use for swarm:  https://github.com/openshiftio/appdev-documentation/pull/92

Maybe this provides useful to you to close the gap

**Comment by gytis** [comment]
Thanks @heiko-braun.

**Comment by rhoads-zach** [comment]
@gytis are you still working on this? If not, do you mind closing it?

**Comment by gytis** [comment]
@rhoads-zach I'm still waiting for Ales to complete health check booster. There might be some Spring Boot specific information to be added once he's done.
