### ISSUE TITLE
Create an Additional Resources Section in the Secured booster guides

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#430]
Since all the other mission have these section, it might help to keep the Secured Mission (despite its slightly different structure) guide consistent and add a similar section to it, too.

**Comment by Ladicek** [comment]
Agreed! There should be a link to Red Hat SSO docs, and I got a link to this wonderful article from @pmlopes that's IMHO a good fit too: https://aaronparecki.com/oauth-2-simplified/

**Comment by inoxx03** [comment]
@Ladicek Thank you for the link, I've created  PR #434 for the resources section.
