### ISSUE TITLE
Consolidate script naming

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#440]
There is a discrepancy in the script naming scheme:

* Most of the scripts in the `scripts` directory and the `buildGuide.sh` scripts are named in camelCase.
* `scripts/deploy_launchpad_mission.sh` and `cico_build_deploy.sh` are named using underscores.

Let's consolidate the naming conventions of the scripts. I suggest we use the all-lowercase, underscore-separated naming:
```
scripts/build_guides.sh
scripts/build_guides_ci.sh
scripts/deploy_launchpad_mission.sh

etc.
```

WDYT?

**Comment by inoxx03** [comment]
resolved in PR #500
