### ISSUE TITLE
Add `compile`option to mvn command when running locally in README

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#445]
update properties file for customized readmes.

Vert.x mission should be
`man compile run....`

**Comment by burrzinga** [comment]
mvn compile vertx:run

this allows for hot redeployment of .java files.   As the file changes, it will auto compile and recycle the Vert.x instance, redeploying the app and the user just needs to hit refresh in his/her browser.

**Comment by rhoads-zach** [comment]
thanks @burrzinga, does this only apply to vert.x, or is this valid on boot and swarm as well?
