### ISSUE TITLE
Finalize interaction on CRUD missions

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#45]
Work with appropriate booster owners to finalize this content

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/crud-mission-database-interaction.adoc

**Comment by rhoads-zach** [comment]
@inoxx03 any updates on this?

**Comment by inoxx03** [comment]
@rhoads-zach Clement had a good point that we should use ```curl``` instead of ```http```, since the latter requires an additional installation step. I'll replace the current CLI command and output examples with examples using ```curl```.

**Comment by rhoads-zach** [comment]
@inoxx03 I believe this PR took care of most of the references:

https://github.com/openshiftio/appdev-documentation/pull/120/files

If these changes resolve this issue, please close this issue.

**Comment by cescoffier** [comment]
@rhoads-zach @inoxx03 I've fixed the command lines to use the correct CURL commands (and output)

The fix is in #131
