### ISSUE TITLE
Add new GitHub labels

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#455]
The repository is missing a few labels:

Guides:
* Contribution Guide
* Minishift Guide
* Getting Started Guide

Priorities:
* High Priority
* Low Priority

Please suggest others. The labels should be added on GitHub and described in the Contrib Guide.

**Comment by inoxx03** [comment]
+ 1

Suggestions:

I see we also have some mission-specific labels:
* Health Check
* CRUD
* REST API
* ConfigMap
* SSO (I'm guessing this denotes the Secured Booster rather that RHSSO per se)

We might want to add a label for the Circuit Breaker Mission, too, for completensess sake

Also, we should consider adding these:

* SME Review Pending
* Peer Review Pending  

Reason: we'd have an easily recognizable way of labeling PR's that have or have not been reviewed. The two new labels above would complement the already existing _Peer Review_ and _SME Review_ labels.

Also:

* Blocker

for high urgency issues.

Lastly, we could add a three-level system based on the estimated level of effort for a task, for example:

* LOE: Low
* LOE: Medium
* LOE: High

This could help make prioritizing issues easier, but feel free to reject this, lest we end up with "too much label" :)

WDYT?

**Comment by gastaldi** [comment]
How about having labels for the runtimes?

**Comment by Ladicek** [comment]
It seems you have quite a lot of labels, so it would probably be good to categorize them by type. I see you already do that with colors, but frankly, the list of labels is still quite hard to read. What I often see is using a prefix (in addition to colors, which is a wonderful idea!). For example:

- Runtime / WildFly Swarm, Runtime / Vert.x, ...
- Mission / REST API, Mission / CRUD, ...
- Type / Bug, Type / Enhancement, Type / Discussion, ...
- Progress / Peer Review Pending, Progress / SME Review Pending, ...
- Effort / Low, Effort / Medium, ...
- Priority / Normal, Priority / Blocker, ...

That way, the labels will be naturally sorted and all labels of given type will be visually together. Which IMHO decreases the required cognitive load quite a bit.

**Comment by tradej** [comment]
@inoxx03:

Thanks for the suggestions, I'm certainly in favour of implementing them. I am not sure if we need the _-pending_ labels for PRs because IMO we could reuse the existing SME/Peer review labels for those reviews that already happened, but it's nothing I would strictly oppose.

@gastaldi:

We have runtime-related labels already.

@Ladicek:

Absolutely, I have to concede the existing system doesn't scale, and it has to. I'm thinking which syntax is most readable:

* `Progress / SME Review Pending`
* `Progress: SME Review Pending`
* `Progress | SME Review Pending`

TBH, I'm a fan of the last option.
