### ISSUE TITLE
Normalize format between missions

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#46]
CRUD missions differ from HTTP API, Configmap, and Healthcheck in the general format and sections (for example, CRUD as tech pre-reqs like Git and Maven versions while others do not). Please determine if that content is needed:

- Across all missions
- In specific missions
- Should be removed

Once a decision is made, please ripple across guides.

**Comment by inoxx03** [comment]
The system requirements table has been removed across all CRUD mission guides in PR #48
