### ISSUE TITLE
 Update hyperlink text to be more descriptive of the link's target

### ISSUE THREAD

**Issue by astrong1** [openshiftio/appdev-documentation#460]
We have three instances of hyperlink text that only contains words like "here". As an example in the section _Trigger Builds Automatically with UltraHook_, we have:

`Sign up for an UltraHook API Key link:http://www.ultrahook.com/register[here] and remember your _namespace_ from the form.`

These hyperlinks should be more descriptive of the target and the "call to action" for the user clicking on the link. In this example, the hyperlink text could contain the phrase "Sign up for an UltraHook API Key"

**Comment by lavernw1** [comment]
Update links to be descriptive. Refer to blog post on subject... 
https://medium.com/@heyoka/dont-use-click-here-f32f445d1021

**Comment by lavernw1** [comment]
@inoxx03 need to verify the change to docs/topics/minishift-install-start-configure-minishift.adoc

**Comment by inoxx03** [comment]
resolved in PR #472
