### ISSUE TITLE
CRUD mission acceptance criteria update request

### ISSUE THREAD

**Issue by gytis** [openshiftio/appdev-documentation#47]
I have a couple of suggestions for CRUD mission acceptance criteria:

1. If PUT/POST payload is of a wrong media type (i.e. not JSON) we should return "415 Unsupported Media Type" rather than "400 Bad Request". This error code is more specific and is returned by default in Spring Boot.
2. I wonder if specifying error response body format is not making things too fine-grained. E.g. Spring Boot has a default JSON format which returns the same information (and a bit more) just with different JSON keys. Providing different error body requires new mapping implementation, which is not hard, but adds extra code which is out of the mission context.

Optional: PUT should allow creating a new record if one doesn't exist. Currently 404 is expected by acceptance criteria. I don't think this is that important, since this booster is not pure REST anyway, therefore marking it as optional.

**Comment by cescoffier** [comment]
1. 415 should be used I agree. It is generally used when there is content negotiation (we don't have this), but we could use it.
2. without providing the basic format we would not be able to have a common test suite. However, as it's error related, let's consider it as a recommendation. Be aware that passing stack traces in error message is a "no-go".
3. It depends on how your ids are constructed. It is considered a bad practice to create entities on `PUT` as the _id_ algorithm can become very complicated. So, I would prefer not pushing this.

**Comment by cescoffier** [comment]
Document updated.
