### ISSUE TITLE
An alternative way of setting :revnumber:

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#470]
The current way of obtaining `:revnumber:` (i. e. the last Git tag in the repo) does not work on http://ci.centos.org because the `.git` directory is not copied to the machine that runs the `cico_build_deploy.sh` script that builds the doc set. There needs to be an alternative way of setting this variable. Off the top of my head, I can think of these:

* **Set the current date.** This has the downside that the date in the documentation may not correspond with the tag in the repository (when the container is rebuilt later than that day). However, I don't think this is a big issue because any time we need to revert to the previous stable release, we just go back in Git history and the first tag we come across will be the latest stable version.

* **Maintain versioning manually.** Meaning that the `:revnumber:` attribute would be hardcoded in `document-attributes.adoc`. The obvious downside is that this must be part of the release train, but my experience from the BxMS team shows that it is not much of a hassle.

* ~~**Set the commit hash.** This is rather ugly and user unfriendly, but also unambiguous.~~

All of these solutions still expect tagging to happen because we need to track which commits we published from in the past.

**Comment by tradej** [comment]
Setting the commit hash may actually not be possible for the same reason—the `.git` directory is not copied to the build machine.

**Comment by rhoads-zach** [comment]
@tradej for now, lets move back to $(date). If we come  up with a better solution, lets re-open or create a new issue.

**Comment by tradej** [comment]
On it.
