### ISSUE TITLE
Make testing an integral part of the build process

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#471]
Currently, the `scripts/buildGuides-CI.sh` test script is not run when the containers are built. Testing the books should be an integral part of the build process. Make changes to the `cico_build_deploy.sh` script so that it either contains or calls `scripts/buildGuides-CI.sh` and can be used in the http://ci.centos.org build chain. 

Partly resolves #297.

**Comment by inoxx03** [comment]
resolved in pr #476
