### ISSUE TITLE
Update internal docs with new deployment process and links

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#477]
Update README and contrib guide with with new deployment instructions and removal of prod branch.

**Comment by rhoads-zach** [comment]
@tradej or @inoxx03 either of you want to take this?

**Comment by tradej** [comment]
I am working on the new README right now, so I'll take it.

**Comment by inoxx03** [comment]
resolved in PR #484

**Comment by tradej** [comment]
The Contrib Guide was not updated, reopening.

**Comment by inoxx03** [comment]
@tradej Are you still working on resolving this, or can I close?
