### ISSUE TITLE
Change the expected proficiency level for the Secured mission to Advanced

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#511]
The complexity of the SSO Secured mission warrants a higher expected proficiency level.

Reasons:
* The mission has multiple alternative modes of interaction (JAR client, `curl`, and web client).
* The web client requires Keycloak realm reconfiguration in order to be accessible, it is not accessible out of the box as is the case with the other missions currently in the catalog.
* The mission expects the user to know how to configure SSO.
* SSO configuration is not within the scope of the mission.

FYI @Ladicek

**Comment by Ladicek** [comment]
I'm +1 on this, but I don't think I'm the one who is able to say "yes we should change this" :-)

**Comment by inoxx03** [comment]
@Ladicek I, too, believe we should let other people weigh in on this decision. Let's have a discussion on it here and make it a docs action item if need be.

**Comment by tradej** [comment]
I can not find a flaw in this reasoning. +1. We should also make this requirements obvious in the introduction of said mission, IMO.

**Comment by inoxx03** [comment]
According to the email discussion, I believe we have reached a consensus.
@tradej +1 on you suggestion.
We'll bump the expected proficiency level for the Secured booster to Advanced and ad a callout to the Mission intro about required knowledge of Keaycloak and SSO configuration.

**Comment by Ladicek** [comment]
Agreed, thanks!

**Comment by inoxx03** [comment]
resolved in PR: #514
