### ISSUE TITLE
validate_guides.sh creates untracked files

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#515]
When `validate_guides.sh` (or by extension `cico_build_deploy.sh`) is run, a `master.xml` file is created in every book directory that was built. These should either be removed upon successful completion, or rather added to `.gitignore` so that they aren't committed by accident.

**Comment by rhoads-zach** [comment]
I cannot reproduce this locally. I don't think my fix for #517 would affect this. @tradej are you still seeing this?

**Comment by tradej** [comment]
The issue persists. #517 is completely unrelated.

@rhoads-zach, can you please run `validate_guides.sh` on `master` and then `find -name master.xml`? I would be very surprised if this turned out with nothing. `git status` should show the files too.

**Comment by rhoads-zach** [comment]
@tradej 
```
$ ./scripts/validate_guides.sh
Running tests...
usage: dirname path


Testing passed.
$ find . -name "master.xml"
$
```

**Comment by tradej** [comment]
@rhoads-zach I know where the problem is—dirname is behaving differently on a Mac than on Linux or BSD.

I'm afraid I'll need you to test the scripts I write, or at least get a Mac somewhere, so that I can test them myself. Running an instance of BSD obviously isn't enough to ensure the scripts work.

I'll file an issue.
