### ISSUE TITLE
cico_build_deploy.sh creates the "html" directory as root

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#517]
When the `cico_build_deploy.sh` script is run, it builds the doc set inside the container with root privileges, therefore creating the `$REPO_HOME/html` directory owned by `root:root`. This makes it impossible for the regular user to build the doc set later using the `build_guides.sh` script as it tries to remove the root-owned directory.

Either the `html` directory should be removed after it serves its purpose in the `cico_build_deploy.sh` script, or its ownership should be set to the regular user who ran the script.

**Comment by rhoads-zach** [comment]
@tradej closing this due to #520
