### ISSUE TITLE
Update description for npm install in Nodejs runtime

### ISSUE THREAD

**Issue by lavernw1** [openshiftio/appdev-documentation#522]
@Ladicek thanks for your review for issue 494. Creating this issue to address your comments regarding npm install -installs packages/dependencies.

**Comment by Ladicek** [comment]
Sure. Just want to make sure: there's really no difference between "installing packages" and "installing dependencies", because "installing dependencies" actually means "installing packages that the present package depends on".

**Comment by inoxx03** [comment]
resolved in PR #523
