### ISSUE TITLE
Add Vert.x Health Check for CI

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-documentation#54]
Continuation of work done in #53 

We could use a Health Check to ensure rolling deployment doesn't roll until the verticle is ready to serve.  Is this not put in place by FMP?

**Comment by ALRubinger** [comment]
Assigning to @cescoffier but you can hit back to me if you can point me to an example of where you set Health Checks and how.  :)

**Comment by cescoffier** [comment]
1) What kind of health check? (probably readiness)
2) How to you want them to be implemented?  - simple route, Vert.x health check ?
3) How do you want them to be declared? - template, oc command (patch), Maven ?

**Comment by cescoffier** [comment]
Ah ah, I was missing the context.

Ok, I will add the health checks :-) (I was thinking it was doc related).

**Comment by ALRubinger** [comment]
@cescoffier Thank you! 	246489e
