### ISSUE TITLE
fix nodejs crud mission wording

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#557]
per @Ladicek in docs/topics/crud-mission-deploy-booster.adoc

L66:
I think we changed this formulation recently (?). This sounds like Nodeshift is used to install dependencies, which isn't exactly correct.

reference: https://github.com/openshiftio/appdev-documentation/pull/546#discussion_r135702249

**Comment by Ladicek** [comment]
This is the commit I had in mind: https://github.com/openshiftio/appdev-documentation/commit/41d29063b23611a6f5a2c87b84bfa421a7f2a0de
