### ISSUE TITLE
Delete is not a trashcan icon in minishift minishift v1.5.0

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#559]
In the "Install and Configure the launch.openshift.io Application on a Single-node OpenShift Cluster" guide in section 2 step 3, "Delete the preconfigured project", you are asked to click the trash can icon to delete the preconfigured project.  In minishift v1.5.0 the option to delete is listed once you click on the 3 stacked dots (indicating a separate menu).

<img width="978" alt="delete option" src="https://user-images.githubusercontent.com/367748/29846970-86870cd0-8cd6-11e7-921f-b48f679f6b2a.png">

**Comment by inoxx03** [comment]
Thanks for catching this:)
In the docs, we still recommend using Minishift version 1.3.1, due to issue with FMP that occur on the later versions.
We'll make the update when we move to using Minishift v 1.5.0.

**Comment by rhoads-zach** [comment]
@inoxx03 @rdruss relates to #450

**Comment by inoxx03** [comment]
More detail on deployment isues in [OBST-352](https://issues.jboss.org/browse/OBST-352)
