### ISSUE TITLE
New Project is now Create Project in minishift 1.5.0

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#560]
In the "Install and Configure the launch.openshift.io Application on a Single-node OpenShift Cluster" guide, section 4.2 Manually, you are asked to click _New Project_ but for minishift 1.5.0 this is now _Create Project_.

<img width="447" alt="create project" src="https://user-images.githubusercontent.com/367748/29847991-7ed2867c-8cdb-11e7-937e-1e89e23c4711.png">

**Comment by inoxx03** [comment]
We currently do not recommend using Minishift v1.5.0 to users, due to issues with the stability of Fabric8 Maven Plugin on this version.

**Comment by rhoads-zach** [comment]
relates #450

**Comment by inoxx03** [comment]
More detail on deployment isues in [OBST-352](https://issues.jboss.org/browse/OBST-352)
