### ISSUE TITLE
Spring Boot circuit breaker doc shouldn't recommend skipping tests

### ISSUE THREAD

**Issue by gytis** [openshiftio/appdev-documentation#561]
When deploying Circuit Breaker booster docs suggest to use the following command `mvn clean fabric8:deploy -Popenshift -DskipTests` (see section 2.5.3 of [1]). It should be `mvn clean fabric8:deploy -Popenshift`

[1] https://appdev.prod-preview.openshift.io/docs/spring-boot-runtime.html

**Comment by inoxx03** [comment]
resolved by PR #568
