### ISSUE TITLE
Different pod names when explaining how to deploy a booster

### ISSUE THREAD

**Issue by gytis** [openshiftio/appdev-documentation#564]
In every Spring Boot booster documentation there is a section explaining how to deploy a booster on OpenShift. It shows an example output of the OpenShift:

```
oc get pods -w
NAME                             READY     STATUS      RESTARTS   AGE
MY_APP_NAME-1-aaaaa       1/1       Running     0          58s
MY_APP_NAME-s2i-1-build   0/1       Completed   0          2m
```

And then explains what status to expect. But in the wording after the example almost always pod name is different than the one in an OpenShift output example e.g. MY_APP_NAME, app1, health-check.

I think the names used in text and examples should be the same throughout the documentation.

**Comment by rhoads-zach** [comment]
fixed in #572
