### ISSUE TITLE
Is "Command Line Tools" section in an obvious location to new OpenShift users?

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#577]
"You can find this in the Command Line Tools section your Single-node OpenShift Cluster Web console."

This implies that the user is aware that the section in question can be found in the question mark drop down to the left of their username.  If I was a new user, this location would be unintuitive to me and I may look to the left menu to find this section.

**Comment by rdruss** [comment]
This same section also mentions, "Get your authentication token for using the oc CLI client with Single-node OpenShift Cluster."

However, as far as I can tell, you can only copy the entire command, *not* just the token

<img width="975" alt="token" src="https://user-images.githubusercontent.com/367748/29895147-4976c8e8-8d95-11e7-954c-58dbf37afbe2.png">

Clicking the clipboard here copies the entire command and not just the token

**Comment by inoxx03** [comment]
resolved in PR #626
