### ISSUE TITLE
Is a discussion of adding view access rights to service account needed?

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#581]
In the Eclipse Vert.x Runtime Guide sections 2.2.3 and 2.2.5 discuss adding view access rights to service account without explanation as to why.  Should there either be a quick explanation in the doc or a link to additional documentation for the user to understand why this is needed?

**Comment by cescoffier** [comment]
For the config map booster, Vert.x requires "read" access to retrieve the content of the config map.

**Comment by Ladicek** [comment]
I'd use a more explicit explanation. Something like: "Vert.x uses the OpenShift API to retrieve the content of the ConfigMap, and hence the service account under which the application runs needs the "read" permissions."

**Comment by inoxx03** [comment]
@Ladicek, @cescoffier @rdruss; IIUC, for the ConfigMap booster (and integration tests), the service account needs to have _read_ permissions, not _view_ permissions, to access the ConfigMap. (Or is it both?)

**Comment by Ladicek** [comment]
So what actually happens is that we add the `view` role to the service account under which the application is running. Maybe we can stay away of mentioning specific role/permission names, stating just "needs permissions to read the configmap" or something.

**Comment by inoxx03** [comment]
resolved in PR #625
