### ISSUE TITLE
2 ways to get application URL

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#589]
In the Eclipse Vert.x Runtime Guide section 2.3.1 step 9 has you get the application URL by using `oc get routes`.  In step 1 of the very next section (2.3.2) the recommendation is to use `oc get route MY_APP_NAME -o jsonpath={$.spec.host}` to get the URL.  Should there either be an explanation about why there are 2 different ways to get the URL demonstrated or standardize on using just 1 way?

**Comment by rhoads-zach** [comment]
@inoxx03 this is part of the CRUD mission. Was there a specific reason for using this different command?

**Comment by Ladicek** [comment]
They are both really the same thing. `oc get route` is more suitable for human (because the user needs to read the output, figure out it's a table, read the correct value from the table) while `oc get route NAME -o ...` is more suitable for scripting (prints just what's required and nothing more).

**Comment by inoxx03** [comment]
@rhoads-zach @Ladicek Thanks:) I'll go with  `oc get route` in this example to keep it consistent with the rest of the docs.

**Comment by inoxx03** [comment]
fixed in #618
