### ISSUE TITLE
CRUD integration tests remove application

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#590]
In section 2.3.3, it might be worth documenting that the integration tests for the Vert.x CRUD booster completely remove the application when the tests are complete.  If you navigate to the application overview page after the tests have been run, you get the "Add to Project" button (i.e. an empty project).

**Comment by rhoads-zach** [comment]
@inoxx03 do you want to take this, or would you like me to grab it?

**Comment by Ladicek** [comment]
I think all integration tests do that. Actually all integration tests also deploy the app, before the test. They are just completely self-contained. (The only exception is the SSO mission, but let's not go there.)

**Comment by inoxx03** [comment]
resolved by PR #619
