### ISSUE TITLE
Fix Install and Configure a Single-node OpenShift Cluster URL

### ISSUE THREAD

**Issue by spisiakm** [openshiftio/appdev-documentation#597]
In (every - at least for Vert.x runtime) **Build and Deploy Your Booster** [section](https://appdev.openshift.io/docs/vertx-runtime.html#rest_build_and_deploy_booster) (and **Deploy your Booster to a Single-node OpenShift Cluster** subsection)

> You can find more details in [Install and Configure a Single-node OpenShift Cluster](https://github.com/minishift/minishift#installation).

the link there points to minishift GitHub repo with focus on element with id `installation`, but there's no such element so you're left at the top of the page. It could be that the element was removed from README. Could it be updated to point to https://github.com/minishift/minishift#welcome-to-minishift or https://docs.openshift.org/latest/minishift/getting-started/index.html for example ? Thanks !

**Comment by Ladicek** [comment]
It should probably point to the Minishift guide: https://appdev.openshift.io/docs/minishift-installation.html
