### ISSUE TITLE
Propose a wiki mission template

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#61]
I think that it would be great that we have within the appdev-documentation.wiki repo an adoc template to help us when we have to add a new mission/booster

**Comment by inoxx03** [comment]
+1 I think this would help maintaining consistency across wiki pages detailing the individual boosters.

**Comment by inoxx03** [comment]
First take at a universal Mission Wiki template https://github.com/openshiftio/appdev-documentation/wiki/Mission-Wiki-Template

@cmoulliard  Please take a look and let me know if anything needs to be fixed. if you find everything ok, please feel free to close this issue.

**Comment by rhoads-zach** [comment]
@cmoulliard can we close this issue?
