### ISSUE TITLE
oc use case - zip download or clone git repo?

### ISSUE THREAD

**Issue by rdruss** [openshiftio/appdev-documentation#615]
In looking at oc-client-deploy-booster-download-note.adoc it's stated that "You must still create a booster using the {launcher} application before you can deploy it using the oc CLI client.".  However, this is not true (at least for Vert.x) as you can just as easily clone the Github repo and follow the exact same steps.  I'm not sure if this note should be changed or if another use case should be documented.

**Comment by rhoads-zach** [comment]
@rdruss I believe we want to direct users to using the launcher since it gives them the customized README files that you would not get if you just cloned the upstream repo. 

Let me know if you feel differently @ALRubinger but closing this for right now.

Feel free to re-open if you want to discuss
