### ISSUE TITLE
Add a TOC to mission wiki pages

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#63]
I propose/suggest that we add a Table Of content section for each booster/mission wiki page.

**Comment by inoxx03** [comment]
It seems that the http://openshiftio-appdev-docs-appdev-documentation.tsrv.devshift.net/(rendered docs) already contain an automatically generated TOC at the top of each mission guide. Is that what you mean?

**Comment by inoxx03** [comment]
@cmoulliard I've added a TOC to all existing Mission Wiki pages. WDYT?
I'll do some consistency fixes to unify the structure of the wiki pages, but please take a look, and let me know if this is ok.

**Comment by inoxx03** [comment]
@cmoulliard I've added  a TOC to all wiki Mission pages (incl. the template). Please take a look an let me know if it looks OK to you and I will close this issue.

**Comment by cmoulliard** [comment]
+1. This is perfect. We can close the ticket.
