### ISSUE TITLE
Consider names of paths in booster creation

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#632]
![new issue](https://user-images.githubusercontent.com/208104/30231851-8d4596fc-94b2-11e7-91ec-15949389b0c0.png)

Given the above, the [GSG](https://appdev.openshift.io/docs/getting-started.html#oso-create-booster) currently says:

> The Use Continuous Delivery option creates a new GitHub repository of your booster and launches it to OpenShift Online while Build and Run Locally creates a ZIP of your booster that you can download to build and run locally. 

We need to decide if we should use the section name (top) or the button name (bottom).

@gastaldi what are your thoughts on making the button and section name consistent

cc @ALRubinger @edewit

**Comment by gastaldi** [comment]
Maybe `Use Continuous Delivery` should be renamed to `Use OpenShift Online` in this case.
