### ISSUE TITLE
Add a level section

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/appdev-documentation#64]
As some missions/boosters will be related or could be part as discussed during f2f meetings of a learning path (= advanced, expert, ...), I propose to add a "Level" section to specify the level to which the mission belongs like also if it is linked to another missions

**Comment by ALRubinger** [comment]
Are you proposing we rank Missions within a Program by difficulty?

**Comment by rhoads-zach** [comment]
@lavernw1 or @tradej would either of you like to grab this issue?

**Comment by tradej** [comment]
I'll take this.

**Comment by cmoulliard** [comment]
We could start by defining 3 levels; foundational*, advanced and expert

* : The Foundation level is the entry level certification which offers you a general awareness of the key elements, concepts and terminology used

Nevertheless, there is a point that we should debate before to assign a level to a mission as we should provide a definition between the different levels and what they are supposed to represent, which competencies I'm supposed to have in order to use an advanced mission, ...
