### ISSUE TITLE
Update nexus repository section based on S2I updates

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#641]
https://appdev.prod-preview.openshift.io/docs/minishift-installation.html#_using_a_nexus_repository_server_with_the_launch_openshift_io_application_on_your_single_node_openshift_cluster

**Comment by rhoads-zach** [comment]
Based on the work in #637, update the nexus repo section

**Comment by inoxx03** [comment]
@rhoads-zach  Thanks, I'll take this:)

**Comment by inoxx03** [comment]
reference:
* [Email thread](https://mail.google.com/mail/u/1/#search/build+and+deploy/15e869b9ad4a0133?compose=15e9b3f1bec9bb0e)

* [OpenShift Docs nexus Guide](https://docs.openshift.com/container-platform/3.5/dev_guide/app_tutorials/maven_tutorial.html)

**Comment by tradej** [comment]
Closed via #664.
