### ISSUE TITLE
Fix link title in crud mission intro

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#648]
Line 3 here
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/crud-mission-intro-paragraph.adoc#L3

is inconsistent with Line 3 here:
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/circuit-breaker-mission-intro-paragraph.adoc

crud mission link should have a title.

**Comment by inoxx03** [comment]
resolved in PR #649
