### ISSUE TITLE
Create Release Notes article on Customer Portal

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#665]
Move the content from the RN google doc.
To remain unpublished until further notice.
Structure based on
 [EAP7 Beta RN](https://access.redhat.com/articles/3036251)

**Comment by inoxx03** [comment]
[Portal article](https://access.redhat.com/articles/3194372) for the RHOAR Beta 2 Release Notes

**Comment by Ladicek** [comment]
By closing this issue, do you mean it's finished? Because I know that at least the Vert.x and Swarm version numbers are for Beta1, not for Beta2. There might be other issues, I didn't review very closely.

**Comment by inoxx03** [comment]
@Ladicek No, the Release Notes article is not finished, there are several sections of the article that still need to be updated and reviewed, including the Supported Maven Artifact versions, Known Issues and the Support Statement.
I'll keep this issue open until all the information in the article has been updated.

**Comment by Ladicek** [comment]
OK, thanks.

**Comment by inoxx03** [comment]
[Beta 2 Release Notes](https://access.redhat.com/articles/3194372) are ready to be published. Closing this issue.
