### ISSUE TITLE
Latest publication is not tagged

### ISSUE THREAD

**Issue by tradej** [openshiftio/appdev-documentation#684]
Please tag the latest commit we published. Thank you.

**Comment by Ladicek** [comment]
Was there a release? It seems yes, but I didn't see an announcement. After tagging, please also send an announcement. Thanks :-)

**Comment by tradej** [comment]
Changed the description from "release" to "publication." The books at appdev.openshift.io/docs list `2017-09-29` as the latest publication, so there was one.

**Comment by inoxx03** [comment]
@tradej Good catch:) Also, since there is no tag yet, there is no way to create a release in the upstream repo. I'll do the tagging if that's ok.

**Comment by inoxx03** [comment]
The [`2017-09-29` release](https://github.com/openshiftio/appdev-documentation/releases/tag/2017-09-29) is now tagged. [Older releases](https://github.com/openshiftio/appdev-documentation/releases) have been added as well.
