### ISSUE TITLE
Move EXP-102 to the Wiki

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/appdev-documentation#69]
content here:
https://docs.google.com/document/d/1RVBSFUCuouKX58SkNeiAnW3qXkD437VUqqaxhbXYHxY/edit#heading=h.oup0rkbi2qat

**Comment by rhoads-zach** [comment]
This is now in the wiki:

https://github.com/openshiftio/appdev-documentation/wiki/Mission:-ConfigMap

closing
