### ISSUE TITLE
Problem with ConfigMap booster acceptance criteria #3

### ISSUE THREAD

**Issue by gytis** [openshiftio/appdev-documentation#84]
Acceptance criteria #3 from https://github.com/openshiftio/appdev-documentation/wiki/Mission:-ConfigMap#acceptance-criteria is not going to work if we use greeting endpoint with readiness probe. After deleting ConfigMap application needs to be restarted, but probe will not succeed because of 500 error.

**Comment by kenfinnigan** [comment]
I don't believe the Mission specifies to use the greeting endpoint as the readiness probe does it?

Why not use `/` for readiness as we're publishing an index.html page there?

**Comment by gytis** [comment]
It doesn't just I thought that was defacto agreement. Good point about /, will use that
