### ISSUE TITLE
[Mission: ConfigMap] SpringBoot-specific Acceptance Criteria

### ISSUE THREAD

**Issue by RadekKoubsky** [openshiftio/appdev-documentation#85]
There is ambiguous reference (Step 2 where?) in [SpringBoot-specific Acceptance Criteria](https://github.com/openshiftio/appdev-documentation/wiki/Mission:-ConfigMap#springboot-specific-acceptance-criteria):

`Step 2 is not required as fabric8-maven-plugin creates this using Spring Cloud Kubernetes`

This is due to last update of the mission. It relates to [Prerequisites](https://github.com/openshiftio/appdev-documentation/wiki/Mission:-ConfigMap#prerequisites)
`The user deploys the configmap for the application: oc create configmap <config_name> --from-file=app-config.yml`

SpringBoot does not require this step (that's the 'Step 2' reference above). We should either have a correct note about it in mission doc or the springboot booster should use the `oc create configmap <config_name> --from-file=app-config.yml` command.

**Comment by rhoads-zach** [comment]
Updated docs with functionality as is in #90

**Comment by rhoads-zach** [comment]
@RadekKoubsky please take a look at the PR and docs and re-open if there are any remaining issues.

**Comment by rhoads-zach** [comment]
@cmoulliard i have documented this as it currently works. Is the plan to update it the booster and make it function like the other configmap boosters?
